/*use amwpspot;*/

drop table if exists WpSpotAccountInfo;
create table WpSpotAccountInfo
(
    id                       bigint        not null comment '主键' primary key,
    accountId                bigint(20)    not null comment 'AM平台账户ID',
    brokerID                 varchar(12)   not null comment '经纪公司代码',
    investorID               varchar(14)   not null comment '投资者帐号',
    investorPassword         varchar(64)   not null comment '投资者密码',
    authCode                 varchar(18)   not null comment '认证码',
    appID                    varchar(34)   not null comment 'App代码',
    mdFrontAddr              varchar(256)  not null comment '行情前置机地址',
    tradeFrontAddr           varchar(256)  not null comment '交易前置机地址',
    unique index (`accountId`, `brokerID`, `investorID`)
) comment '外盘现货投资者帐号表';

drop table if exists WpSpotTradingAccount;
create table WpSpotTradingAccount
(
    id                                      bigint                   not null comment '主键' primary key,
    accountId                               bigint(20)               not null comment 'AM平台账户ID',
    BrokerID                                varchar(12)              not null comment '经纪公司代码',
    InvestorID                              varchar(14)              not null comment '投资者帐号(对应CTP中AccountID)',
    PreMortgage                             decimal(22, 8) default 0 not null comment '上次质押金额',
    PreCredit                               decimal(22, 8) default 0 not null comment '上次信用额度',
    PreDeposit                              decimal(22, 8) default 0 not null comment '上次存款额',
    PreBalance                              decimal(22, 8) default 0 not null comment '上次结算准备金',
    PreMargin                               decimal(22, 8) default 0 not null comment '上次占用的保证金',
    InterestBase                            decimal(22, 8) default 0 not null comment '利息基数',
    Interest                                decimal(22, 8) default 0 not null comment '利息收入',
    Deposit                                 decimal(22, 8) default 0 not null comment '入金金额',
    Withdraw                                decimal(22, 8) default 0 not null comment '出金金额',
    FrozenMargin                            decimal(22, 8) default 0 not null comment '冻结的保证金',
    FrozenCash                              decimal(22, 8) default 0 not null comment '冻结的资金',
    FrozenCommission                        decimal(22, 8) default 0 not null comment '冻结的手续费',
    CurrMargin                              decimal(22, 8) default 0 not null comment '当前保证金总额',
    CashIn                                  decimal(22, 8) default 0 not null comment '资金差额',
    Commission                              decimal(22, 8) default 0 not null comment '手续费',
    CloseProfit                             decimal(22, 8) default 0 not null comment '平仓盈亏',
    PositionProfit                          decimal(22, 8) default 0 not null comment '持仓盈亏',
    Balance                                 decimal(22, 8) default 0 not null comment '期货结算准备金',
    Available                               decimal(22, 8) default 0 not null comment '可用资金',
    WithdrawQuota                           decimal(22, 8) default 0 not null comment '可取资金',
    Reserve                                 decimal(22, 8) default 0 not null comment '基本准备金',
    TradingDay                              varchar(10)              not null comment '交易日',
    SettlementID                            int(11)                  not null comment '结算编号',
    Credit                                  decimal(22, 8) default 0 not null comment '信用额度',
    Mortgage                                decimal(22, 8) default 0 not null comment '质押金额',
    ExchangeMargin                          decimal(22, 8) default 0 not null comment '交易所保证金',
    DeliveryMargin                          decimal(22, 8) default 0 not null comment '投资者交割保证金',
    ExchangeDeliveryMargin                  decimal(22, 8) default 0 not null comment '交易所交割保证金',
    ReserveBalance                          decimal(22, 8) default 0 not null comment '保底期货结算准备金',
    CurrencyID                              varchar(5)               not null comment '币种代码',
    PreFundMortgageIn                       decimal(22, 8) default 0 not null comment '上次货币质入金额',
    PreFundMortgageOut                      decimal(22, 8) default 0 not null comment '上次货币质出金额',
    FundMortgageIn                         	decimal(22, 8) default 0 not null comment '货币质入金额',
    FundMortgageOut                         decimal(22, 8) default 0 not null comment '货币质出金额',
    FundMortgageAvailable                   decimal(22, 8) default 0 not null comment '货币质押余额',
    MortgageableFund                        decimal(22, 8) default 0 not null comment '可质押货币金额',
    SpecProductMargin                       decimal(22, 8) default 0 not null comment '特殊产品占用保证金',
    SpecProductFrozenMargin                 decimal(22, 8) default 0 not null comment '特殊产品冻结保证金',
    SpecProductCommission                   decimal(22, 8) default 0 not null comment '特殊产品手续费',
    SpecProductFrozenCommission             decimal(22, 8) default 0 not null comment '特殊产品冻结手续费',
    SpecProductPositionProfit               decimal(22, 8) default 0 not null comment '特殊产品持仓盈亏',
    SpecProductCloseProfit                  decimal(22, 8) default 0 not null comment '特殊产品平仓盈亏',
    SpecProductPositionProfitByAlg          decimal(22, 8) default 0 not null comment '根据持仓盈亏算法计算的特殊产品持仓盈亏',
    SpecProductExchangeMargin               decimal(22, 8) default 0 not null comment '特殊产品交易所保证金',
    BizType                                 char(1)                  not null comment '业务类型(业务类型类型数据字典)',
    FrozenSwap                              decimal(22, 8) default 0 not null comment '延时换汇冻结金额',
    RemainSwap                              decimal(22, 8) default 0 not null comment '剩余换汇额度',
    unique index (`accountId`, `BrokerID`, `InvestorID`, `CurrencyID`)
) comment '外盘现货资金账户息表';

-- drop table if exists WpSpotInstrumentMarginRate;
-- create table WpSpotInstrumentMarginRate
-- (
--     id                          bigint                              not null comment '主键' primary key,
--     accountId                   bigint(20)                          not null comment 'AM平台账户ID',
--     brokerID                    varchar(12)                         not null comment '经纪公司代码',
--     investorID                  varchar(14)                         not null comment '投资者帐号',
--     instrumentID                varchar(32)                         not null comment '合约代码(可以是品种，也可以是具体合约)',
--     investorRange               char                                not null comment '投资者范围',
--     hedgeFlag                   char                                not null comment '投机套保标志',
--     longMarginRatioByMoney      decimal(22, 8) default 0.00000000   not null comment '多头保证金率',
--     longMarginRatioByVolume     decimal(22, 8) default 0.00000000   not null comment '多头保证金费',
--     shortMarginRatioByMoney     decimal(22, 8) default 0.00000000   not null comment '空头保证金率',
--     shortMarginRatioByVolume    decimal(22, 8) default 0.00000000   not null comment '空头保证金费',
--     isRelative                  int(11)                             not null comment '是否相对交易所收取',
--     exchangeID                  varchar(10)                         not null comment '交易所代码',
--     investUnitID                varchar(18)                         not null comment '投资单元代码',
--     unique index (`accountId`, `brokerID`, `investorID`, `instrumentID`, `hedgeFlag`)
-- ) comment '外盘现货合约保证金率表';

drop table if exists WpSpotInstrumentCommissionRate;
create table WpSpotInstrumentCommissionRate
(
    id                          bigint                              not null comment '主键' primary key,
    accountId                   bigint(20)                          not null comment 'AM平台账户ID',
    brokerID                    varchar(12)                         not null comment '经纪公司代码',
    investorID                  varchar(14)                         not null comment '投资者帐号',
    instrumentID                varchar(32)                                  comment '合约代码',
    investorRange               char                                         comment '投资者范围',
    OpenRatioByMoney            decimal(22, 8) default 0.00000000   not null comment '开仓手续费率',
    OpenRatioByVolume           decimal(22, 8) default 0.00000000   not null comment '开仓手续费',
    CloseRatioByMoney           decimal(22, 8) default 0.00000000   not null comment '平仓手续费率',
    CloseRatioByVolume          decimal(22, 8) default 0.00000000   not null comment '平仓手续费',
    CloseTodayRatioByMoney      decimal(22, 8) default 0.00000000   not null comment '平今手续费率',
    CloseTodayRatioByVolume     decimal(22, 8) default 0.00000000   not null comment '平今手续费',
    exchangeID                  varchar(10)                                  comment '交易所代码',
    bizType                     char                                         comment '业务类型',
    investUnitID                varchar(18)                                  comment '投资单元代码',
    unique index (`accountId`, `brokerID`, `investorID`, `instrumentID`)
) comment '外盘现货合约手续费率表';

-- drop table if exists WpSpotInstrumentOrderCommRate;
-- create table WpSpotInstrumentOrderCommRate
-- (
--     id                          bigint                              not null comment '主键' primary key,
--     accountId                   bigint(20)                          not null comment 'AM平台账户ID',
--     brokerID                    varchar(12)                         not null comment '经纪公司代码',
--     investorID                  varchar(14)                         not null comment '投资者帐号',
--     instrumentID                varchar(32)                         not null comment '合约代码(可以是品种，也可以是具体合约)',
--     investorRange               char                                not null comment '投资者范围',
--     hedgeFlag                   char                                not null comment '投机套保标志',
--     OrderCommByVolume           decimal(22, 8) default 0.00000000   not null comment '报单手续费',
--     OrderActionCommByVolume     decimal(22, 8) default 0.00000000   not null comment '撤单手续费',
--     exchangeID                  varchar(10)                         not null comment '交易所代码',
--     investUnitID                varchar(18)                         not null comment '投资单元代码',
--     unique index (`accountId`, `brokerID`, `investorID`, `instrumentID`, `hedgeFlag`)
-- ) comment '外盘现货报单手续费表(中金所持有)';

-- drop table if exists WpSpotBrokerTradingParams;
-- create table WpSpotBrokerTradingParams
-- (
--     id                          bigint                              not null comment '主键' primary key,
--     accountId                   bigint(20)                          not null comment 'AM平台账户ID',
--     brokerID                    varchar(12)                         not null comment '经纪公司代码',
--     investorID                  varchar(14)                         not null comment '投资者帐号',
--     marginPriceType             char                                not null comment '保证金价格类型',
--     algorithm                   char                                not null comment '盈亏算法',
--     availIncludeCloseProfit     char                                not null comment '可用是否包含平仓盈利',
--     currencyID                  varchar(5)                          not null comment '币种代码',
--     optionRoyaltyPriceType      char                                not null comment '期权权利金价格类型',
--     accountNo                   varchar(14)                         not null comment '投资者帐号(对应AccountID)',
--     unique index (`accountId`, `brokerID`, `investorID`)
-- ) comment '外盘现货经纪公司交易参数表';

drop table if exists WpSpotInvestorPositionDetail;
create table WpSpotInvestorPositionDetail
(
    id                       bigint                    not null comment '主键' primary key,
    accountId                bigint(20)                not null comment 'AM平台账户ID',
    InstrumentID             varchar(32)               not null comment '合约代码',
    BrokerID                 varchar(12)               not null comment '经纪公司代码',
    InvestorID               varchar(14)               not null comment '投资者代码',
    HedgeFlag                char(1)                   not null comment '投机套保标志(投机套保标志类型数据字典)',
    Direction                char(1)                   not null comment '买卖(买卖方向类型数据字典)',
    OpenDate                 varchar(10)               not null comment '开仓日期',
    TradeID                  varchar(22)               not null comment '成交编号',
    Volume                   int(11)                   not null comment '数量',
    OpenPrice                decimal(22, 8) default 0  not null comment '开仓价',
    TradingDay               varchar(10)               not null comment '交易日',
    SettlementID             int(11)                   not null comment '结算编号',
    TradeType                char(1)                   not null comment '成交类型(成交类型类型数据字典)',
    CombInstrumentID         varchar(32)               not null comment '组合合约代码',
    ExchangeID               varchar(10)               not null comment '交易所代码',
    CloseProfitByDate        decimal(22, 8) default 0  not null comment '逐日盯市平仓盈亏',
    CloseProfitByTrade       decimal(22, 8) default 0  not null comment '逐笔对冲平仓盈亏',
    PositionProfitByDate     decimal(22, 8) default 0  not null comment '逐日盯市持仓盈亏',
    PositionProfitByTrade    decimal(22, 8) default 0  not null comment '逐笔对冲持仓盈亏',
    Margin                   decimal(22, 8) default 0  not null comment '投资者保证金',
    ExchMargin               decimal(22, 8) default 0  not null comment '交易所保证金',
    MarginRateByMoney        decimal(22, 8) default 0  not null comment '保证金率',
    MarginRateByVolume       decimal(22, 8) default 0  not null comment '保证金率(按手数)',
    LastSettlementPrice      decimal(22, 8) default 0  not null comment '昨结算价',
    SettlementPrice          decimal(22, 8) default 0  not null comment '结算价',
    CloseVolume              int(11)                   not null comment '平仓量',
    CloseAmount              decimal(22, 8) default 0  not null comment '平仓金额',
    TimeFirstVolume          int(11)                   not null comment '先开先平剩余数量（DCE）',
    InvestUnitID             varchar(18)               not null comment '投资单元代码',
    SpecPosiType             char(1)                            comment '特殊持仓标志(特殊持仓明细标识类型数据字典)',
    unique index (`accountId`, `InstrumentID`, `Direction`, `TradeID`, `TradeType`, `OpenDate`, `HedgeFlag`)
) comment '外盘现货持仓明细表';

drop table if exists WpSpotInvestorPosition;
create table WpSpotInvestorPosition
(
    id                       bigint                   not null comment '主键' primary key,
    accountId                bigint(20)               not null comment 'AM平台账户ID',
    InstrumentID             varchar(32)              not null comment '合约代码',
    BrokerID                 varchar(12)              not null comment '经纪公司代码',
    InvestorID               varchar(14)              not null comment '投资者代码',
    PosiDirection            char(1)                  not null comment '持仓多空方向(持仓多空方向类型数据字典)',
    HedgeFlag                char(1)                  not null comment '投机套保标志(投机套保标志类型数据字典)',
    PositionDate             char(1)                  not null comment '持仓日期(持仓日期类型数据字典)',
    YdPosition               int(11)                  not null comment '上日持仓',
    Position                 int(11)                  not null comment '今日持仓',
    LongFrozen               int(11)                  not null comment '多头冻结',
    ShortFrozen              int(11)                  not null comment '空头冻结',
    LongFrozenAmount         decimal(22, 8) default 0 not null comment '开仓冻结金额',
    ShortFrozenAmount        decimal(22, 8) default 0 not null comment '开仓冻结金额',
    OpenVolume               int(11)                  not null comment '开仓量',
    CloseVolume              int(11)                  not null comment '平仓量',
    OpenAmount               decimal(22, 8) default 0 not null comment '开仓金额',
    CloseAmount              decimal(22, 8) default 0 not null comment '平仓金额',
    PositionCost             decimal(22, 8) default 0 not null comment '持仓成本',
    PreMargin                decimal(22, 8) default 0 not null comment '上次占用的保证金',
    UseMargin                decimal(22, 8) default 0 not null comment '占用的保证金',
    FrozenMargin             decimal(22, 8) default 0 not null comment '冻结的保证金',
    FrozenCash               decimal(22, 8) default 0 not null comment '冻结的资金',
    FrozenCommission         decimal(22, 8) default 0 not null comment '冻结的手续费',
    CashIn                   decimal(22, 8) default 0 not null comment '资金差额',
    Commission               decimal(22, 8) default 0 not null comment '手续费',
    CloseProfit              decimal(22, 8) default 0 not null comment '平仓盈亏',
    PositionProfit           decimal(22, 8) default 0 not null comment '持仓盈亏',
    PreSettlementPrice       decimal(22, 8) default 0 not null comment '上次结算价',
    SettlementPrice          decimal(22, 8) default 0 not null comment '本次结算价',
    TradingDay               varchar(10)              not null comment '交易日',
    SettlementID             int(11)                  not null comment '结算编号',
    OpenCost                 decimal(22, 8) default 0 not null comment '开仓成本',
    ExchangeMargin           decimal(22, 8) default 0 not null comment '交易所保证金',
    CombPosition             int(11)                  not null comment '组合成交形成的持仓',
    CombLongFrozen           int(11)                  not null comment '组合多头冻结',
    CombShortFrozen          int(11)                  not null comment '组合空头冻结',
    CloseProfitByDate        decimal(22, 8) default 0 not null comment '逐日盯市平仓盈亏',
    CloseProfitByTrade       decimal(22, 8) default 0 not null comment '逐笔对冲平仓盈亏',
    TodayPosition            int(11)                  not null comment '今日持仓',
    MarginRateByMoney        decimal(22, 8) default 0 not null comment '保证金率',
    MarginRateByVolume       decimal(22, 8) default 0 not null comment '保证金率(按手数)',
    StrikeFrozen             int(11)                  not null comment '执行冻结',
    StrikeFrozenAmount       decimal(22, 8) default 0 not null comment '执行冻结金额',
    AbandonFrozen            int(11)                  not null comment '放弃执行冻结',
    ExchangeID               varchar(10)              not null comment '交易所代码',
    YdStrikeFrozen           int(11)                  not null comment '执行冻结的昨仓',
    InvestUnitID             varchar(18)              not null comment '投资单元代码',
    PositionCostOffset       decimal(22, 8) default 0 not null comment '大商所持仓成本差值，只有大商所使用',
    TasPosition              int(11)                  not null comment 'tas持仓手数',
    TasPositionCost          decimal(22, 8) default 0 not null comment 'tas持仓成本',
    unique index (`accountId`, `BrokerID`, `InvestorID`, `InstrumentID`, `PosiDirection`, `PositionDate`, `HedgeFlag`)
) comment '外盘现货持仓汇总表';

drop table if exists WpSpotOrder;
create table WpSpotOrder
(
    id                    bigint                   not null comment '主键' primary key,
    accountId             bigint(20)               not null comment 'AM平台账户ID',
    BrokerID              varchar(12)              not null comment '经纪公司代码',
    InvestorID            varchar(14)              not null comment '投资者代码',
    InstrumentID          varchar(32)              not null comment '合约代码',
    OrderRef              varchar(14)              not null comment '报单引用',
    UserID                varchar(17)              not null comment '用户代码',
    OrderPriceType        char(1)                  not null comment '报单价格条件(报单价格条件类型数据字典)',
    Direction             char(1)                  not null comment '买卖方向(0买、1卖)',
    CombOffsetFlag        varchar(6)               not null comment '组合开平标志',
    CombHedgeFlag         varchar(6)               not null comment '组合投机套保标志',
    LimitPrice            decimal(22, 8) default 0 not null comment '价格',
    VolumeTotalOriginal   int(11)                  not null comment '数量',
    TimeCondition         char(1)                  not null comment '有效期类型',
    GTDDate               varchar(10)                       comment 'GTD日期',
    VolumeCondition       char(1)                  not null comment '成交量类型(成交量类型类型数据字典)',
    MinVolume             int(11)                  not null comment '最小成交量',
    ContingentCondition   char(1)                  not null comment '触发条件(触发条件类型数据字典)',
    StopPrice             decimal(22, 8) default 0 not null comment '止损价',
    ForceCloseReason      char(1)                  not null comment '强平原因(强平原因类型数据字典)',
    IsAutoSuspend         int(11)                  not null comment '自动挂起标志',
    BusinessUnit          varchar(22)                       comment '业务单元',
    RequestID             int(11)                  not null comment '请求编号',
    OrderLocalID          varchar(14)              			comment '本地报单编号',
    ExchangeID            varchar(10)              not null comment '交易所代码',
    ParticipantID         varchar(12)              			comment '会员代码',
    ClientID              varchar(12)                       comment '客户代码',
    ExchangeInstID        varchar(32)              			comment '合约在交易所的代码',
    TraderID              varchar(22)              			comment '交易所交易员代码',
    InstallID             int(11)                  			comment '安装编号',
    OrderSubmitStatus     char(1)                  			comment '报单提交状态(报单提交状态类型数据字典)',
    NotifySequence        int(11)                  			comment '报单提示序号',
    TradingDay            varchar(10)              			comment '交易日',
    SettlementID          int(11)                  			comment	'结算编号',
    OrderSysID            varchar(22)              			comment '报单编号',
    OrderSource           char(1)                  			comment	'报单来源(报单来源类型数据字典)',
    OrderStatus           char(1)                  			comment '报单状态(报单状态类型数据字典)',
    OrderType             char(1)                  			comment '报单类型(报单类型类型数据字典)',
    VolumeTraded          int(11)                  			comment '今成交数量',
    VolumeTotal           int(11)                  			comment '剩余数量',
    InsertDate            varchar(10)              			comment '报单日期',
    InsertTime            varchar(10)              			comment '委托时间',
    ActiveTime            varchar(10)              			comment '激活时间',
    SuspendTime           varchar(10)              			comment '挂起时间',
    UpdateTime            varchar(10)              			comment '最后修改时间',
    CancelTime            varchar(10)              			comment '撤销时间',
    ActiveTraderID        varchar(22)              			comment '最后修改交易所交易员代码',
    ClearingPartID        varchar(12)              			comment '结算会员编号',
    SequenceNo            int(11)                  			comment '序号',
    FrontID               int(11)                  			comment '前置编号',
    SessionID             int(11)                  			comment '会话编号',
    UserProductInfo       varchar(12)              			comment '用户端产品信息',
    StatusMsg             varchar(82)              			comment '状态信息',
    UserForceClose        int(11)                  not null comment '用户强评标志',
    ActiveUserID          varchar(17)              			comment '操作用户代码',
    BrokerOrderSeq        int(11)                  			comment '经纪公司报单编号',
    RelativeOrderSysID    varchar(22)              			comment '相关报单',
    ZCETotalTradedVolume  int(11)                  			comment '郑商所成交数量',
    IsSwapOrder           int(11)                  			comment '互换单标志',
    BranchID              varchar(10)              			comment '营业部编号',
    InvestUnitID          varchar(18)                       comment '投资单元代码',
    AccountNo             varchar(22)                       comment '资金账户代码(对应AccountID)',
    CurrencyID            varchar(5)                        comment '币种代码',
    IPAddress             varchar(17)                       comment 'IP地址',
    MacAddress            varchar(22)                       comment 'Mac地址',
    ErrorID			  	  int(11)				   			comment '错误代码',
    ErrorMsg		  	  varchar(82)				   		comment '错误信息',
    OrderActionRef		  int(11)				   			comment '报单操作引用',
    ActionFlag			  char(1)				   			comment '操作标志',
    VolumeChange		  int(11)				   			comment '数量变化',
    ActionDate			  varchar(10)				   		comment '操作日期',
    ActionTime		  	  varchar(10)				   		comment '操作时间',
    ActionLocalID		  varchar(14)				   		comment '操作本地编号',
    OrderActionStatus	  char(1)				   			comment '报单操作状态',
    unique index (`accountId`, `FrontID`, `SessionID`, `OrderRef`)
) comment '外盘现货委托订单表';

drop table if exists WpSpotTrade;
create table WpSpotTrade
(
    id                  bigint                   not null comment '主键' primary key,
    accountId           bigint(20)               not null comment 'AM平台账户ID',
    BrokerID            varchar(12)              not null comment '经纪公司代码',
    InvestorID          varchar(14)              not null comment '投资者代码',
    InstrumentID        varchar(32)              not null comment '合约代码',
    OrderRef            varchar(14)              not null comment '报单引用',
    UserID              varchar(17)              not null comment '用户代码',
    ExchangeID          varchar(10)              not null comment '交易所代码',
    TradeID             varchar(22)              not null comment '成交编号',
    Direction           char(1)                  not null comment '买卖方向(买卖方向类型数据字典)',
    OrderSysID          varchar(22)              not null comment '报单编号',
    ParticipantID       varchar(12)                       comment '会员代码',
    ClientID            varchar(12)                       comment '客户代码',
    TradingRole         char(1)                           comment '交易角色(交易角色类型数据字典)',
    ExchangeInstID      varchar(32)                       comment '合约在交易所的代码',
    OffsetFlag          char(1)                  not null comment '开平标志(开平标志类型数据字典)',
    HedgeFlag           char(1)                  not null comment '投机套保标志(投机套保标志类型数据字典)',
    Price               decimal(22, 8) default 0 not null comment '价格',
    Volume              int(11)                  not null comment '数量',
    TradeDate           varchar(10)              not null comment '成交日期',
    TradeTime           varchar(10)              not null comment '成交时间',
    TradeType           char(1)                  not null comment '成交类型(成交类型类型数据字典)',
    PriceSource         char(1)                           comment '成交价来源(成交价来源类型数据字典)',
    TraderID            varchar(22)                       comment '交易所交易员代码',
    OrderLocalID        varchar(14)                       comment '本地报单编号',
    ClearingPartID      varchar(12)                       comment '结算会员编号',
    BusinessUnit        varchar(22)                       comment '业务单元',
    SequenceNo          int(11)                  not null comment '序号',
    TradingDay          varchar(10)              not null comment '交易日',
    SettlementID        int(11)                  not null comment '结算编号',
    BrokerOrderSeq      int(11)                  not null comment '经纪公司报单编号',
    TradeSource         char(1)                           comment '成交来源(成交来源类型数据字典)',
    InvestUnitID        varchar(18)                       comment '投资单元代码',
    unique index (`accountId`, `ExchangeID`, `TradeID`, `Direction`)
) comment '外盘现货成交表';

drop table if exists WpSpotOrderHis;
create table WpSpotOrderHis
(
    id                    bigint                   not null comment '主键' primary key,
    accountId             bigint(20)               not null comment 'AM平台账户ID',
    BrokerID              varchar(12)              not null comment '经纪公司代码',
    InvestorID            varchar(14)              not null comment '投资者代码',
    InstrumentID          varchar(32)              not null comment '合约代码',
    OrderRef              varchar(14)              not null comment '报单引用',
    UserID                varchar(17)              not null comment '用户代码',
    OrderPriceType        char(1)                  not null comment '报单价格条件(报单价格条件类型数据字典)',
    Direction             char(1)                  not null comment '买卖方向(0买、1卖)',
    CombOffsetFlag        varchar(6)               not null comment '组合开平标志',
    CombHedgeFlag         varchar(6)               not null comment '组合投机套保标志',
    LimitPrice            decimal(22, 8) default 0 not null comment '价格',
    VolumeTotalOriginal   int(11)                  not null comment '数量',
    TimeCondition         char(1)                  not null comment '有效期类型',
    GTDDate               varchar(10)                       comment 'GTD日期',
    VolumeCondition       char(1)                  not null comment '成交量类型(成交量类型类型数据字典)',
    MinVolume             int(11)                  not null comment '最小成交量',
    ContingentCondition   char(1)                  not null comment '触发条件(触发条件类型数据字典)',
    StopPrice             decimal(22, 8) default 0 not null comment '止损价',
    ForceCloseReason      char(1)                  not null comment '强平原因(强平原因类型数据字典)',
    IsAutoSuspend         int(11)                  not null comment '自动挂起标志',
    BusinessUnit          varchar(22)                       comment '业务单元',
    RequestID             int(11)                  not null comment '请求编号',
    OrderLocalID          varchar(14)              			comment '本地报单编号',
    ExchangeID            varchar(10)              not null comment '交易所代码',
    ParticipantID         varchar(12)              			comment '会员代码',
    ClientID              varchar(12)                       comment '客户代码',
    ExchangeInstID        varchar(32)              			comment '合约在交易所的代码',
    TraderID              varchar(22)              			comment '交易所交易员代码',
    InstallID             int(11)                  			comment '安装编号',
    OrderSubmitStatus     char(1)                  			comment '报单提交状态(报单提交状态类型数据字典)',
    NotifySequence        int(11)                  			comment '报单提示序号',
    TradingDay            varchar(10)              			comment '交易日',
    SettlementID          int(11)                  			comment	'结算编号',
    OrderSysID            varchar(22)              			comment '报单编号',
    OrderSource           char(1)                  			comment	'报单来源(报单来源类型数据字典)',
    OrderStatus           char(1)                  			comment '报单状态(报单状态类型数据字典)',
    OrderType             char(1)                  			comment '报单类型(报单类型类型数据字典)',
    VolumeTraded          int(11)                  			comment '今成交数量',
    VolumeTotal           int(11)                  			comment '剩余数量',
    InsertDate            varchar(10)              			comment '报单日期',
    InsertTime            varchar(10)              			comment '委托时间',
    ActiveTime            varchar(10)              			comment '激活时间',
    SuspendTime           varchar(10)              			comment '挂起时间',
    UpdateTime            varchar(10)              			comment '最后修改时间',
    CancelTime            varchar(10)              			comment '撤销时间',
    ActiveTraderID        varchar(22)              			comment '最后修改交易所交易员代码',
    ClearingPartID        varchar(12)              			comment '结算会员编号',
    SequenceNo            int(11)                  			comment '序号',
    FrontID               int(11)                  			comment '前置编号',
    SessionID             int(11)                  			comment '会话编号',
    UserProductInfo       varchar(12)              			comment '用户端产品信息',
    StatusMsg             varchar(82)              			comment '状态信息',
    UserForceClose        int(11)                  not null comment '用户强评标志',
    ActiveUserID          varchar(17)              			comment '操作用户代码',
    BrokerOrderSeq        int(11)                  			comment '经纪公司报单编号',
    RelativeOrderSysID    varchar(22)              			comment '相关报单',
    ZCETotalTradedVolume  int(11)                  			comment '郑商所成交数量',
    IsSwapOrder           int(11)                  			comment '互换单标志',
    BranchID              varchar(10)              			comment '营业部编号',
    InvestUnitID          varchar(18)                       comment '投资单元代码',
    AccountNo             varchar(22)                       comment '资金账户代码(对应AccountID)',
    CurrencyID            varchar(5)                        comment '币种代码',
    IPAddress             varchar(17)                       comment 'IP地址',
    MacAddress            varchar(22)                       comment 'Mac地址',
    ErrorID			  	  int(11)				   			comment '错误代码',
    ErrorMsg		  	  varchar(82)				   		comment '错误信息',
    OrderActionRef		  int(11)				   			comment '报单操作引用',
    ActionFlag			  char(1)				   			comment '操作标志',
    VolumeChange		  int(11)				   			comment '数量变化',
    ActionDate			  varchar(10)				   		comment '操作日期',
    ActionTime		  	  varchar(10)				   		comment '操作时间',
    ActionLocalID		  varchar(14)				   		comment '操作本地编号',
    OrderActionStatus	  char(1)				   			comment '报单操作状态',
    unique index (`accountId`, `FrontID`, `SessionID`, `OrderRef`)
) comment '外盘现货委托订单历史表';
