/*use amnpfutures;*/

drop table if exists EsNpfuturesAccountInfo;
create table EsNpfuturesAccountInfo
(
    id                       bigint        not null comment '主键' primary key,
    accountId                bigint(20)    not null comment 'AM平台账户ID',
    brokerNo                 varchar(12)   not null comment '经纪商编码',
    accountNo                varchar(20)   not null comment '资金账号',
    accountState             char(1)       not null comment '账号状态',
    accountShortName         varchar(20)            comment '账号简称',
    accountIsDocHolder       char(1)       not null comment '是否持证者',
    isMarketMaker            char(1)       not null comment '是否是做市商',
    accountFamilyType        char(1)                comment '父子账号类型',
    accountPassword          varchar(20)   not null comment '资金账号密码',
    authCode                 varchar(50)   not null comment '资金账号授权码',
    appID                    varchar(30)   not null comment '程序版本号',
    quoteApiAddr             varchar(256)  not null comment '行情前置机地址',
    tradeApiAddr             varchar(256)  not null comment '交易前置机地址',
    unique index (`accountId`, `brokerNo`, `accountNo`)
) comment '内盘期货资金账号表';

drop table if exists EsNpfuturesFundData;
create table EsNpfuturesFundData
(
    id                          bigint                   not null comment '主键' primary key,
    accountId                   bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                    varchar(12)              not null comment '经纪商编码',
    accountNo                   varchar(20)              not null comment '客户资金账号',
    parentAccountNo             varchar(20)                       comment '上级资金账号',
    currencyGroupNo             varchar(10)              not null comment '币种组号',
    currencyNo                  varchar(10)              not null comment '币种号(为空表示币种组基币资金)',
    tradeRate                   decimal(22, 8) default 0 not null comment '交易汇率',
    futureAlg                   char(1)                  not null comment '期货算法',
    optionAlg                   char(1)                  not null comment '期权算法',
    preBalance                  decimal(22, 8) default 0 not null comment '上日结存',
    preUnExpProfit              decimal(22, 8) default 0 not null comment '上日未到期平盈',
    preLMEPositionProfit        decimal(22, 8) default 0 not null comment '上日LME持仓平盈',
    preEquity                   decimal(22, 8) default 0 not null comment '上日权益',
    preAvailable1               decimal(22, 8) default 0 not null comment '上日可用',
    preMarketEquity             decimal(22, 8) default 0 not null comment '上日市值权益',
    cashInValue                 decimal(22, 8) default 0 not null comment '入金',
    cashOutValue                decimal(22, 8) default 0 not null comment '出金',
    cashAdjustValue             decimal(22, 8) default 0 not null comment '资金调整',
    cashPledged                 decimal(22, 8) default 0 not null comment '质押资金',
    frozenFee                   decimal(22, 8) default 0 not null comment '冻结手续费',
    frozenDeposit               decimal(22, 8) default 0 not null comment '冻结保证金',
    accountFee                  decimal(22, 8) default 0 not null comment '客户手续费包含交割手续费',
	exchangeFee                 decimal(22, 8) default 0 not null comment '汇兑手续费',
	accountDeliveryFee          decimal(22, 8) default 0 not null comment '客户交割手续费',
    premiumIncome               decimal(22, 8) default 0 not null comment '权利金收取',
    premiumPay                  decimal(22, 8) default 0 not null comment '权利金支付',
    closeProfit                 decimal(22, 8) default 0 not null comment '平仓盈亏',
    deliveryProfit              decimal(22, 8) default 0 not null comment '交割盈亏',
    unExpProfit                 decimal(22, 8) default 0 not null comment '未到期平盈',
    expProfit                   decimal(22, 8) default 0 not null comment '到期平仓盈亏',
    positionProfit              decimal(22, 8) default 0 not null comment '不含LME持仓盈亏',
    lmePositionProfit           decimal(22, 8) default 0 not null comment 'LME持仓盈亏',
    optionMarketValue           decimal(22, 8) default 0 not null comment '期权市值',
    accountIntialMargin         decimal(22, 8) default 0 not null comment '客户初始保证金',
    accountMaintenanceMargin    decimal(22, 8) default 0 not null comment '客户维持保证金',
    upperInitalMargin           decimal(22, 8) default 0 not null comment '上手初始保证金',
    upperMaintenanceMargin      decimal(22, 8) default 0 not null comment '上手维持保证金',
    discount                    decimal(22, 8) default 0 not null comment 'LME贴现',
    balance                     decimal(22, 8) default 0 not null comment '当日结存',
    equity                      decimal(22, 8) default 0 not null comment '当日权益',
    available                   decimal(22, 8) default 0 not null comment '当日可用',
    canDraw                     decimal(22, 8) default 0 not null comment '可提取',
    marketEquity                decimal(22, 8) default 0 not null comment '账户市值',
	originalCashInOut           decimal(22, 8) default 0 not null comment '币种原始出入金',
	floatingPL                  decimal(22, 8) default 0 not null comment '逐笔浮盈',
	frozenRiskFundValue         decimal(22, 8) default 0 not null comment '风险冻结资金',
	closePL                     decimal(22, 8) default 0 not null comment '逐笔平盈',
	noCurrencyPledgeValue       decimal(22, 8) default 0 not null comment '非货币质押',
	prePledgeValue              decimal(22, 8) default 0 not null comment '期初质押',
	pledgeIn                    decimal(22, 8) default 0 not null comment '质入',
	pledgeOut                   decimal(22, 8) default 0 not null comment '质出',
	pledgeValue                 decimal(22, 8) default 0 not null comment '质押余额',
	borrowValue                 decimal(22, 8) default 0 not null comment '借用金额',
	specialAccountFrozenMargin  decimal(22, 8) default 0 not null comment '特殊产品冻结保证金',
	specialAccountMargin        decimal(22, 8) default 0 not null comment '特殊产品保证金',
	specialAccountFrozenFee     decimal(22, 8) default 0 not null comment '特殊产品冻结手续费',
	specialAccountFee           decimal(22, 8) default 0 not null comment '特殊产品手续费',
	specialFloatProfit          decimal(22, 8) default 0 not null comment '特殊产品浮盈',
	specialCloseProfit          decimal(22, 8) default 0 not null comment '特殊产品平盈',
	specialFloatPL              decimal(22, 8) default 0 not null comment '特殊产品逐笔浮盈',
	specialClosePL              decimal(22, 8) default 0 not null comment '特殊产品逐笔平盈',
    unique index (`accountId`, `brokerNo`, `accountNo`, `currencyNo`)
) comment '内盘期货资金账号资金信息表';

drop table if exists EsNpfuturesAccountRentInfo;
create table EsNpfuturesAccountRentInfo
(
    id                  bigint                              not null comment '主键' primary key,
    accountId           bigint(20)                          not null comment 'AM平台账户ID',
    brokerNo            varchar(12)                         not null comment '经纪商编码',
    accountNo           varchar(20)                         not null comment '客户资金账号',
    exchangeNo          varchar(10)                         not null comment '交易所编码',
    commodityType       char                                not null comment '品种类型',
    commodityNo         varchar(10)                         not null comment '品种编号',
    contractNo          varchar(10)                         not null comment '合约代码',
    matchSource         char                                not null comment '成交来源',
    currencyNo          varchar(10)                         not null comment '币种编号',
    feeMode             char                                not null comment '手续费计算方式1.比例,2.定额,7.绝对方式(期货公司设置)',
    openTurnover        decimal(22, 8) default 0.00000000   not null comment '开仓手续费按金额',
    closedTurnover      decimal(22, 8) default 0.00000000   not null comment '平仓手续费按金额',
    closeNewTurnover    decimal(22, 8) default 0.00000000   not null comment '平今手续费按金额',
    openVolume          decimal(22, 8) default 0.00000000   not null comment '开仓手续费按手数',
    closedVolume        decimal(22, 8) default 0.00000000   not null comment '平仓手续费按手数',
    closeNewVolume      decimal(22, 8) default 0.00000000   not null comment '平今手续费按手数',
    marginMode          char                                not null comment '保证金计算方式(1.比例,2.定额,7.绝对方式(期货公司设置))',
    buyTInitMargin      decimal(22, 8) default 0.00000000   not null comment '买投机初始保证金',
    sellTInitMargin     decimal(22, 8) default 0.00000000   not null comment '卖投机初始保证金',
    buyBInitMargin      decimal(22, 8) default 0.00000000   not null comment '买保值初始保证金',
    sellBInitMargin     decimal(22, 8) default 0.00000000   not null comment '卖保值初始保证金',
    buyLInitMargin      decimal(22, 8) default 0.00000000   not null comment '买套利初始保证金',
    sellLInitMargin     decimal(22, 8) default 0.00000000   not null comment '卖套利初始保证金',
    buyMInitMargin      decimal(22, 8) default 0.00000000   not null comment '买做市商初始保证金',
    sellMInitMargin     decimal(22, 8) default 0.00000000   not null comment '卖做市商初始保证金',
    buyTMaintMargin     decimal(22, 8) default 0.00000000   not null comment '买投机维持保证金',
    sellTMaintMargin    decimal(22, 8) default 0.00000000   not null comment '卖投机维持保证金',
    buyBMaintMargin     decimal(22, 8) default 0.00000000   not null comment '买保值维持保证金',
    sellBMaintMargin    decimal(22, 8) default 0.00000000   not null comment '卖保值维持保证金',
    buyLMaintMargin     decimal(22, 8) default 0.00000000   not null comment '买套利维持保证金',
    sellLMaintMargin    decimal(22, 8) default 0.00000000   not null comment '卖套利维持保证金',
    buyMMaintMargin     decimal(22, 8) default 0.00000000   not null comment '买做市商维持保证金',
    sellMMaintMargin    decimal(22, 8) default 0.00000000   not null comment '卖做市商维持保证金',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `commodityType`, `commodityNo`, `contractNo`)
) comment '内盘期货客户费率表';

drop table if exists EsNpfuturesPositionInfo;
create table EsNpfuturesPositionInfo
(
    id                       bigint                   not null comment '主键' primary key,
    accountId                bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                 varchar(12)              not null comment '经纪商编码',
    accountNo                varchar(20)              not null comment '客户资金帐号',
    parentAccountNo          varchar(20)              not null comment '上级资金账号',
    exchangeNo               varchar(10)              not null comment '交易所编号',
    commodityType            char(1)                  not null comment '品种类型',
    commodityNo              varchar(10)              not null comment '品种编码类型',
    contractNo               varchar(10)              not null comment '合约1',
    strikePrice              varchar(10)              not null comment '执行价格',
    callOrPutFlag            char(1)                  not null comment '看张看跌',
    exchangeNoRef            varchar(10)              not null comment '交易所编号',
	commodityTypeRef         char(1)                  not null comment '品种类型',
	commodityNoRef           varchar(10)              not null comment '品种编码类型',
	contractNoRef            varchar(10)              not null comment '合约',
	strikePriceRef           varchar(10)              not null comment '执行价格',
	callOrPutFlagRef         char(1)                  not null comment '看张看跌',
	orderExchangeNo          varchar(10)              not null comment '交易所编号',
	orderCommodityType       char(1)                  not null comment '品种类型',
	orderCommodityNo         varchar(10)              not null comment '品种编码类型',
	orderType                char(1)                  not null comment '委托类型',
	matchSource              char(1)                  not null comment '委托来源',
	timeInForce              char(1)                  not null comment '委托有效类型',
	expireTime               varchar(20)              not null comment '有效日期(GTD情况下使用)',
	matchSide                char(1)                  not null comment '买入卖出',
	hedgeFlag                char(1)                  not null comment '投机保值',
	positionNo               varchar(70)              not null comment '本地持仓号，服务器编写',
	serverFlag               char(1)                  not null comment '服务器标识',
	orderNo                  varchar(20)              not null comment '委托编码',
	matchNo                  varchar(20)              not null comment '本地成交号',
	exchangeMatchNo          varchar(70)              not null comment '交易所成交号',
	matchDate                varchar(11)              not null comment '成交日期',
	matchTime                varchar(20)              not null comment '成交时间',
	upperMatchTime           varchar(20)              not null comment '上手成交时间',
	upperNo                  varchar(10)              not null comment '上手号',
	upperSettleNo            varchar(20)              not null comment '会员号和清算代码',
	upperUserNo              varchar(20)              not null comment '上手登录号',
	tradeNo                  varchar(10)              not null comment '交易编码',
	positionPrice            decimal(22, 8) default 0 not null comment '持仓价',
	positionQty              int(11)        default 0 not null comment '持仓量',
	isBackInput              char(1)                  not null comment '是否为录入委托单',
	isAddOne                 char(1)                  not null comment '是否为T+1单',
	matchStreamID            int(11)        default 0 not null comment '成交流水号',
    positionStreamId         int(11)        default 0 not null comment '持仓流号',
    openCloseMode            char(1)                  not null comment '开平方式',
	contractSize             decimal(22, 8) default 0 not null comment '每手乘数，计算参数',
	commodityCurrencyGroup   varchar(20)              not null comment '品种币种组',
	commodityCurrency        varchar(20)              not null comment '品种币种',
	preSettlePrice           decimal(22, 8) default 0 not null comment '昨结算价',
	settlePrice              decimal(22, 8) default 0 not null comment '当前计算价格',
	turnover                 decimal(22, 8) default 0 not null comment '持仓金额',
	accountMarginMode        char(1)                  not null comment '保证金计算方式',
	accountMarginParam       decimal(22, 8) default 0 not null comment '保证金参数值',
	upperMarginMode          char(1)                  not null comment '保证金计算方式',
	upperMarginParam         decimal(22, 8) default 0 not null comment '保证金参数值',
	accountInitialMargin     decimal(22, 8) default 0 not null comment '客户初始保证金',
	accountMaintenanceMargin decimal(22, 8) default 0 not null comment '客户维持保证金',
	upperInitialMargin       decimal(22, 8) default 0 not null comment '上手初始保证金',
	upperMaintenanceMargin   decimal(22, 8) default 0 not null comment '上手维持保证金',
	positionProfit           decimal(22, 8) default 0 not null comment '持仓盈亏',
	lMEPositionProfit        decimal(22, 8) default 0 not null comment 'LME持仓盈亏',
	optionMarketValue        decimal(22, 8) default 0 not null comment '期权市值',
	matchCmbNo               varchar(20)              not null comment '组合持仓号',
	isHistory                char(1)                  not null comment '是否历史持仓',
	floatingPL               decimal(22, 8) default 0 not null comment '逐笔浮盈',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `commodityNo`, `contractNo`, `positionNo`)
) comment '内盘期货持仓明细表';


drop table if exists EsNpfuturesOrderInfo;
create table EsNpfuturesOrderInfo
(
    id                          bigint                   not null comment '主键' primary key,
    accountId                   bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                    varchar(12)              not null comment '经纪商编码',
    accountNo                   varchar(20)              not null comment '客户资金帐号',
    exchangeNo                  varchar(10)              not null comment '交易所编号',
    commodityType               char(1)                  not null comment '品种类型',
    commodityNo                 varchar(10)              not null comment '品种编码类型',
    contractNo                  varchar(10)              not null comment '合约1',
    strikePrice                 varchar(10)              not null comment '执行价格1',
    callOrPutFlag               char(1)                  not null comment '看张看跌1',
    contractNo2                 varchar(10)              not null comment '合约2',
    strikePrice2                varchar(10)              not null comment '执行价格2',
    callOrPutFlag2              char(1)                  not null comment '看张看跌2',
    orderType                   char(1)                  not null comment '委托类型',
    orderSource                 char(1)                  not null comment '委托来源',
    timeInForce                 char(1)                  not null comment '委托有效类型',
    expireTime                  varchar(32)              not null comment '有效日期(GTD情况下使用)',
    isRiskOrder                 char(1)                  not null comment '是否风险报单',
    orderSide                   char(1)                  not null comment '买入卖出',
    positionEffect              char(1)                  not null comment '开平标志1',
    positionEffect2             char(1)                  not null comment '开平标志2',
    inquiryNo                   varchar(50)              not null comment '询价号',
    hedgeFlag                   char(1)                  not null comment '投机保值',
    orderPrice                  decimal(22, 8) default 0 not null comment '委托价格1',
    orderPrice2                 decimal(22, 8) default 0 not null comment '委托价格2，做市商应价使用',
    stopPrice                   decimal(22, 8) default 0 not null comment '触发价格',
    orderQty                    int(11)        default 0 not null comment '委托数量',
    orderMinQty                 int(11)        default 0 not null comment '最小成交量',
    orderCanceledQty            int(11)        default 0 not null comment '撤单数量',
    minClipSize                 int(11)        default 0 not null comment '冰山单最小随机量',
    maxClipSize                 int(11)        default 0 not null comment '冰山单最大随机量',
    licenseNo                   varchar(50)              not null comment '软件授权号',
    refInt                      int(11)        default 0 not null comment '整型参考值',
    refString                   varchar(50)              not null comment '字符串参考值',
    parentAccountNo             varchar(20)              not null comment '上级资金账号',
    serverFlag                  char(1)                  not null comment '服务器标识',
    orderNo                     varchar(20)              not null comment '委托编码',
    clientOrderNo               varchar(50)              not null comment '客户端本地委托编号',
    orderLocalNo                varchar(20)              not null comment '本地号',
    orderSystemNo               varchar(50)              not null comment '系统号',
    orderExchangeSystemNo       varchar(50)              not null comment '交易所系统号',
    orderParentNo               varchar(20)              not null comment '父单号',
    orderParentSystemNo         varchar(50)              not null comment '父单系统号',
    tradeNo                     varchar(10)              not null comment '交易编码',
    upperNo                     varchar(10)              not null comment '上手号',
    upperChannelNo              varchar(10)              not null comment '上手通道号',
    upperSettleNo               varchar(10)              not null comment '会员号和清算号',
    upperUserNo                 varchar(10)              not null comment '上手登录号',
    orderInsertUserNo           varchar(20)              not null comment '下单人',
    orderInsertTime             varchar(32)              not null comment '下单时间',
    orderCommandUserNo          varchar(20)              not null comment '录单操作人',
    orderUpdateUserNo           varchar(20)              not null comment '委托更新人',
    orderUpdateTime             varchar(32)              not null comment '委托更新时间',
    orderState                  char(1)                  not null comment '委托状态',
    orderMatchPrice             decimal(22, 8) default 0 not null comment '成交价1',
    orderMatchPrice2            decimal(22, 8) default 0 not null comment '成交价2',
    orderMatchQty               int(11)        default 0 not null comment '成交量1',
    orderMatchQty2              int(11)        default 0 not null comment '成交量2',
    errorCode                   int(11)        default 0 not null comment '最后一次操作错误信息码',
    errorText                   varchar(50)              not null comment '错误信息',
    isBackInput                 char(1)                  not null comment '是否为录入委托单',
    isDeleted                   char(1)                  not null comment '委托成交删除标',
    isAddOne                    char(1)                  not null comment '是否为T+1单',
    orderStreamID               int(11)        default 0 not null comment '委托流水号',
    upperStreamID               int(11)                  not null comment '上手流号',
    contractSize                decimal(22, 8) default 0 not null comment '每手乘数，计算参数',
	contractSize2               decimal(22, 8) default 0 not null comment '每手乘数，计算参数',
	commodityCurrencyGroup      varchar(10)              not null comment '品种币种组',
	commodityCurrency           varchar(10)              not null comment '品种币种',
	feeMode                     char(1)                  not null comment '手续费计算方式',
	feeParam                    decimal(22, 8) default 0 not null comment '手续费参数值 冻结手续费均按照开仓手续费计算',
	feeCurrencyGroup            varchar(10)              not null comment '客户手续费币种组',
	feeCurrency                 varchar(10)              not null comment '客户手续费币种',
	feeMode2                    char(1)                  not null comment '手续费计算方式',
	feeParam2                   decimal(22, 8) default 0 not null comment '手续费参数值 冻结手续费均按照开仓手续费计算',
	feeCurrencyGroup2		    varchar(10)              not null comment '客户手续费币种组',
	feeCurrency2				varchar(10)              not null comment '客户手续费币种',
	marginMode                  char(1)                  not null comment '保证金计算方式',
	marginParam                 decimal(22, 8) default 0 not null comment '保证金参数值',
	marginMode2                 char(1)                  not null comment '保证金计算方式',
	marginParam2                decimal(22, 8) default 0 not null comment '保证金参数值',
	preSettlePrice              decimal(22, 8) default 0 not null comment '昨结算价  比例方式的市价单和组合订单使用',
	preSettlePrice2             decimal(22, 8) default 0 not null comment '昨结算价  比例方式的市价单和组合订单使用',
	openVol                     int(11)        default 0 not null comment '预开仓数量 委托数量中的开仓部分',
	coverVol                    int(11)        default 0 not null comment '预平仓数量 委托数量中的平仓部分',
	openVol2				    int(11)        default 0 not null comment '预开仓数量 委托数量中的开仓部分',
	coverVol2                   int(11)        default 0 not null comment '预平仓数量 委托数量中的平仓部分',
	feeValue                    decimal(22, 8) default 0 not null comment '冻结手续费',
	marginValue                 decimal(22, 8) default 0 not null comment '冻结保证金 合并计算的此项为0',
	tacticsType                 char(1)                  not null comment '策略单类型',
	triggerCondition            char(1)                  not null comment '触发条件',
	triggerPriceType            char(1)                  not null comment '触发价格类型',
	addOneIsValid               char(1)                  not null comment '是否T+1有效',
	orderQty2                   int(11)        default 0 not null comment '委托数量2',
	hedgeFlag2                  char(1)                  not null comment '投机保值2',
	marketLevel                 char(1)                  not null comment '市价撮合深度',
    orderDeleteByDisConnFlag    char(1)                  not null comment '心跳检测失败时，服务器自动撤单标识',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `contractNo`, `orderNo`)
) comment '内盘盘期货委托订单表';


drop table if exists EsNpfuturesFillInfo;
create table EsNpfuturesFillInfo
(
    id                      bigint                   not null comment '主键' primary key,
    accountId               bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                varchar(12)              not null comment '经纪商编码',
    accountNo               varchar(20)              not null comment '客户资金帐号',
	parentAccountNo         varchar(20)              not null comment '上级资金账号',
	exchangeNo              varchar(10)              not null comment '交易所编号',
	commodityType           char(1)                  not null comment '品种类型',
	commodityNo             varchar(10)              not null comment '品种编码类型',
	contractNo              varchar(10)              not null comment '合约1',
	strikePrice             varchar(10)              not null comment '执行价格',
	callOrPutFlag           char(1)                  not null comment '看张看跌',
	exchangeNoRef           varchar(10)              not null comment '交易所编号',
	commodityTypeRef        char(1)                  not null comment '品种类型',
	commodityNoRef          varchar(10)              not null comment '品种编码类型',
	contractNoRef           varchar(10)              not null comment '合约',
	strikePriceRef          varchar(10)              not null comment '执行价格',
	callOrPutFlagRef        char(1)                  not null comment '看张看跌',
	orderExchangeNo         varchar(10)              not null comment '交易所编号',
	orderCommodityType      char(1)                  not null comment '品种类型',
	orderCommodityNo        varchar(10)              not null comment '品种编码类型',
	orderType               char(1)                  not null comment '委托类型',
	matchSource             char(1)                  not null comment '委托来源',
	timeInForce             char(1)                  not null comment '委托有效类型',
	expireTime              varchar(20)              not null comment '有效日期(GTD情况下使用)',
	isRiskOrder             char(1)                  not null comment '是否风险报单',
	matchSide               char(1)                  not null comment '买入卖出',
	positionEffect          char(1)                  not null comment '开平标志1',
	positionEffectRef       char(1)                  not null comment '开平标志2',
	hedgeFlag               char(1)                  not null comment '投机保值',
	serverFlag              char(1)                  not null comment '服务器标识',
	orderNo                 varchar(20)              not null comment '委托编码',
	orderLocalNo            varchar(20)              not null comment '委托本地号',
	matchNo                 varchar(20)              not null comment '本地成交号',
	exchangeMatchNo         varchar(70)              not null comment '交易所成交号',
	matchDateTime           varchar(20)              not null comment '成交时间',
	upperMatchDateTime      varchar(20)              not null comment '上手成交时间',
	upperNo                 varchar(10)              not null comment '上手号',
	upperChannelNo          varchar(10)              not null comment '上手通道号',
	upperSettleNo           varchar(20)              not null comment '会员号和清算代码',
	upperUserNo             varchar(20)              not null comment '上手登录号',
	tradeNo                 varchar(10)              not null comment '交易编码',
	matchPrice              decimal(22, 8) default 0 not null comment '成交价',
	matchQty                int(11)                  not null comment '成交量',
	isBackInput             char(1)                  not null comment '是否为录入委托单',
	isDeleted               char(1)                  not null comment '委托成交删除标',
	isAddOne                char(1)                  not null comment '是否为T+1单',
	matchStreamID           int(11)                  not null comment '委托流水号',
	upperStreamID           int(11)                  not null comment '上手流号',
	openCloseMode           char(1)                  not null comment '开平方式',
	contractSize            decimal(22, 8) default 0 not null comment '每手乘数，计算参数',
	commodityCurrencyGroup  varchar(10)              not null comment '品种币种组',
	commodityCurrency       varchar(10)              not null comment '品种币种',
	feeMode                 char(1)                  not null comment '手续费计算方式',
	feeParam                decimal(22, 8) default 0 not null comment '手续费参数值 冻结手续费均按照开仓手续费计算',
	feeCurrencyGroup        varchar(10)              not null comment '客户手续费币种组',
	feeCurrency             varchar(10)              not null comment '客户手续费币种',
	preSettlePrice          decimal(22, 8) default 0 not null comment '昨结算价',
	feeValue                decimal(22, 8) default 0 not null comment '手续费',
	isManualFee             char(1)                  not null comment '人工客户手续费标记',
	turnover                decimal(22, 8) default 0 not null comment '成交金额',
	premiumIncome           decimal(22, 8) default 0 not null comment '权利金收取',
	premiumPay              decimal(22, 8) default 0 not null comment '权利金支付',
	oppoMatchNo             varchar(10)              not null comment '对手本地成交号（开仓和平仓对应编号）',
	closeProfit             decimal(22, 8) default 0 not null comment '平仓盈亏',
	unExpProfit             decimal(22, 8) default 0 not null comment '未到期平盈',
	upperMatchPrice         decimal(22, 8) default 0 not null comment '上手成交价',
	quotePrice              decimal(22, 8) default 0 not null comment '当前行情价',
	closePL                 decimal(22, 8) default 0 not null comment '逐笔平盈',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `contractNo`, `matchNo`)
) comment '内盘期货成交表';


drop table if exists EsNpfuturesCloseInfo;
create table EsNpfuturesCloseInfo
(
    id                      bigint                   not null comment '主键' primary key,
    accountId               bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                varchar(12)              not null comment '经纪商编码',
    accountNo               varchar(20)              not null comment '客户资金帐号',
	parentAccountNo         varchar(20)              not null comment '上级资金账号',
	exchangeNo              varchar(10)              not null comment '交易所编号',
	commodityType           char(1)                  not null comment '品种类型',
	commodityNo             varchar(10)              not null comment '品种编码类型',
	contractNo              varchar(10)              not null comment '合约',
	strikePrice             varchar(10)              not null comment '执行价格',
	callOrPutFlag           char(1)                  not null comment '看张看跌',
	openOrderExchangeNo     varchar(10)              not null comment '交易所编号',
	openOrderCommodityType  char(1)                  not null comment '品种类型',
	openOrderCommodityNo    varchar(10)              not null comment '品种编码类型',
	closeOrderExchangeNo    varchar(10)              not null comment '交易所编号',
	closeOrderCommodityType char(1)                  not null comment '品种类型',
	closeOrderCommodityNo   varchar(10)              not null comment '品种编码类型',
	openMatchSource         char(1)                  not null comment 'OpenMatchSource',
	closeMatchSource        char(1)                  not null comment 'CloseMatchSource',
	closeSide               char(1)                  not null comment '平仓一边的买入卖出',
	closeQty                int(11)                  not null comment '平仓成交量',
	openPrice               decimal(22, 8) default 0 not null comment '开仓成交价',
	closePrice              decimal(22, 8) default 0 not null comment '平仓成交价',
	openServerFlag          char(1)                  not null comment '服务器标识',
	openOrderNo             varchar(20)              not null comment '委托编码',
	openMatchNo             varchar(20)              not null comment '本地成交号',
	openExchangeMatchNo     varchar(70)              not null comment '交易所成交号',
	openMatchDateTime       varchar(20)              not null comment '成交时间',
	closeServerFlag         char(1)                  not null comment '服务器标识',
	closeOrderNo            varchar(20)              not null comment '委托编码',
	closeMatchNo            varchar(20)              not null comment '本地成交号',
	closeExchangeMatchNo    varchar(70)              not null comment '交易所成交号',
	closeMatchDateTime      varchar(20)              not null comment '成交时间',
    closeStreamId           int(11)                  not null comment '平仓流号',
    openCloseMode           char(1)                  not null comment '开平方式',
	contractSize            decimal(22, 8) default 0 not null comment '每手乘数，计算参数',
	commodityCurrencyGroup  varchar(10)              not null comment '品种币种组',
	commodityCurrency       varchar(10)              not null comment '品种币种',
	preSettlePrice          decimal(22, 8) default 0 not null comment '昨结算价',
	premiumIncome           decimal(22, 8) default 0 not null comment '权利金收取',
	premiumPay              decimal(22, 8) default 0 not null comment '权利金支付',
	closeProfit             decimal(22, 8) default 0 not null comment '平仓盈亏',
	unExpProfit             decimal(22, 8) default 0 not null comment '未到期平盈',
	closePL                 decimal(22, 8) default 0 not null comment '逐笔平盈',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `contractNo`, `closeMatchNo`)
) comment '内盘期货平仓记录表';


drop table if exists EsNpfuturesOrderInfoHis;
create table EsNpfuturesOrderInfoHis
(
    id                          bigint                   not null comment '主键' primary key,
    accountId                   bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                    varchar(12)              not null comment '经纪商编码',
    accountNo                   varchar(20)              not null comment '客户资金帐号',
    exchangeNo                  varchar(10)              not null comment '交易所编号',
    commodityType               char(1)                  not null comment '品种类型',
    commodityNo                 varchar(10)              not null comment '品种编码类型',
    contractNo                  varchar(10)              not null comment '合约1',
    strikePrice                 varchar(10)              not null comment '执行价格1',
    callOrPutFlag               char(1)                  not null comment '看张看跌1',
    contractNo2                 varchar(10)              not null comment '合约2',
    strikePrice2                varchar(10)              not null comment '执行价格2',
    callOrPutFlag2              char(1)                  not null comment '看张看跌2',
    orderType                   char(1)                  not null comment '委托类型',
    orderSource                 char(1)                  not null comment '委托来源',
    timeInForce                 char(1)                  not null comment '委托有效类型',
    expireTime                  varchar(32)              not null comment '有效日期(GTD情况下使用)',
    isRiskOrder                 char(1)                  not null comment '是否风险报单',
    orderSide                   char(1)                  not null comment '买入卖出',
    positionEffect              char(1)                  not null comment '开平标志1',
    positionEffect2             char(1)                  not null comment '开平标志2',
    inquiryNo                   varchar(50)              not null comment '询价号',
    hedgeFlag                   char(1)                  not null comment '投机保值',
    orderPrice                  decimal(22, 8) default 0 not null comment '委托价格1',
    orderPrice2                 decimal(22, 8) default 0 not null comment '委托价格2，做市商应价使用',
    stopPrice                   decimal(22, 8) default 0 not null comment '触发价格',
    orderQty                    int(11)        default 0 not null comment '委托数量',
    orderMinQty                 int(11)        default 0 not null comment '最小成交量',
    orderCanceledQty            int(11)        default 0 not null comment '撤单数量',
    minClipSize                 int(11)        default 0 not null comment '冰山单最小随机量',
    maxClipSize                 int(11)        default 0 not null comment '冰山单最大随机量',
    licenseNo                   varchar(50)              not null comment '软件授权号',
    refInt                      int(11)        default 0 not null comment '整型参考值',
    refString                   varchar(50)              not null comment '字符串参考值',
    parentAccountNo             varchar(20)              not null comment '上级资金账号',
    serverFlag                  char(1)                  not null comment '服务器标识',
    orderNo                     varchar(20)              not null comment '委托编码',
    clientOrderNo               varchar(50)              not null comment '客户端本地委托编号',
    orderLocalNo                varchar(20)              not null comment '本地号',
    orderSystemNo               varchar(50)              not null comment '系统号',
    orderExchangeSystemNo       varchar(50)              not null comment '交易所系统号',
    orderParentNo               varchar(20)              not null comment '父单号',
    orderParentSystemNo         varchar(50)              not null comment '父单系统号',
    tradeNo                     varchar(10)              not null comment '交易编码',
    upperNo                     varchar(10)              not null comment '上手号',
    upperChannelNo              varchar(10)              not null comment '上手通道号',
    upperSettleNo               varchar(10)              not null comment '会员号和清算号',
    upperUserNo                 varchar(10)              not null comment '上手登录号',
    orderInsertUserNo           varchar(20)              not null comment '下单人',
    orderInsertTime             varchar(32)              not null comment '下单时间',
    orderCommandUserNo          varchar(20)              not null comment '录单操作人',
    orderUpdateUserNo           varchar(20)              not null comment '委托更新人',
    orderUpdateTime             varchar(32)              not null comment '委托更新时间',
    orderState                  char(1)                  not null comment '委托状态',
    orderMatchPrice             decimal(22, 8) default 0 not null comment '成交价1',
    orderMatchPrice2            decimal(22, 8) default 0 not null comment '成交价2',
    orderMatchQty               int(11)        default 0 not null comment '成交量1',
    orderMatchQty2              int(11)        default 0 not null comment '成交量2',
    errorCode                   int(11)        default 0 not null comment '最后一次操作错误信息码',
    errorText                   varchar(50)              not null comment '错误信息',
    isBackInput                 char(1)                  not null comment '是否为录入委托单',
    isDeleted                   char(1)                  not null comment '委托成交删除标',
    isAddOne                    char(1)                  not null comment '是否为T+1单',
    orderStreamID               int(11)        default 0 not null comment '委托流水号',
    upperStreamID               int(11)                  not null comment '上手流号',
    contractSize                decimal(22, 8) default 0 not null comment '每手乘数，计算参数',
    contractSize2               decimal(22, 8) default 0 not null comment '每手乘数，计算参数',
    commodityCurrencyGroup      varchar(10)              not null comment '品种币种组',
    commodityCurrency           varchar(10)              not null comment '品种币种',
    feeMode                     char(1)                  not null comment '手续费计算方式',
    feeParam                    decimal(22, 8) default 0 not null comment '手续费参数值 冻结手续费均按照开仓手续费计算',
    feeCurrencyGroup            varchar(10)              not null comment '客户手续费币种组',
    feeCurrency                 varchar(10)              not null comment '客户手续费币种',
    feeMode2                    char(1)                  not null comment '手续费计算方式',
    feeParam2                   decimal(22, 8) default 0 not null comment '手续费参数值 冻结手续费均按照开仓手续费计算',
    feeCurrencyGroup2           varchar(10)              not null comment '客户手续费币种组',
    feeCurrency2                varchar(10)              not null comment '客户手续费币种',
    marginMode                  char(1)                  not null comment '保证金计算方式',
    marginParam                 decimal(22, 8) default 0 not null comment '保证金参数值',
    marginMode2                 char(1)                  not null comment '保证金计算方式',
    marginParam2                decimal(22, 8) default 0 not null comment '保证金参数值',
    preSettlePrice              decimal(22, 8) default 0 not null comment '昨结算价  比例方式的市价单和组合订单使用',
    preSettlePrice2             decimal(22, 8) default 0 not null comment '昨结算价  比例方式的市价单和组合订单使用',
    openVol                     int(11)        default 0 not null comment '预开仓数量 委托数量中的开仓部分',
    coverVol                    int(11)        default 0 not null comment '预平仓数量 委托数量中的平仓部分',
    openVol2                    int(11)        default 0 not null comment '预开仓数量 委托数量中的开仓部分',
    coverVol2                   int(11)        default 0 not null comment '预平仓数量 委托数量中的平仓部分',
    feeValue                    decimal(22, 8) default 0 not null comment '冻结手续费',
    marginValue                 decimal(22, 8) default 0 not null comment '冻结保证金 合并计算的此项为0',
    tacticsType                 char(1)                  not null comment '策略单类型',
    triggerCondition            char(1)                  not null comment '触发条件',
    triggerPriceType            char(1)                  not null comment '触发价格类型',
    addOneIsValid               char(1)                  not null comment '是否T+1有效',
    orderQty2                   int(11)        default 0 not null comment '委托数量2',
    hedgeFlag2                  char(1)                  not null comment '投机保值2',
    marketLevel                 char(1)                  not null comment '市价撮合深度',
    orderDeleteByDisConnFlag    char(1)                  not null comment '心跳检测失败时，服务器自动撤单标识',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `contractNo`, `orderNo`)
) comment '内盘期货委托订单历史表';
