/*use amwpfutures;*/

drop table if exists WpfuturesAccountInfo;
create table WpfuturesAccountInfo
(
    id                       bigint        not null comment '主键' primary key,
    accountId                bigint(20)    not null comment 'AM平台账户ID',
    brokerNo                 varchar(12)   not null comment '经纪商编码',
    accountNo                varchar(20)   not null comment '资金账号',
    accountType              char(1)       not null comment '账号类型',
    accountState             char(1)       not null comment '账号状态',
    accountTradeRight        char(1)       not null comment '交易状态',
    commodityGroupNo         varchar(10)   not null comment '可交易品种组',
    accountShortName         varchar(20)            comment '账号简称',
    accountEnShortName       varchar(20)            comment '账号英文简称',
    accountPassword          varchar(64)   not null comment '资金账号密码',
    accountAuthCode          varchar(1024) not null comment '资金账号授权码',
    quoteAccountNo           varchar(20)            comment '行情资金账号',
    quoteAccountPassword     varchar(64)            comment '行情资金账号密码',
    quoteAccountAuthCode     varchar(1024)          comment '行情资金账号授权码',
    quoteApiAddr             varchar(256)  not null comment '行情前置机地址',
    tradeApiAddr             varchar(256)  not null comment '交易前置机地址',
    unique index (`accountId`, `brokerNo`, `accountNo`)
) comment '外盘期货资金账号表';

drop table if exists WpfuturesFundData;
create table WpfuturesFundData
(
    id                       bigint                   not null comment '主键' primary key,
    accountId                bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                 varchar(12)              not null comment '经纪商编码',
    accountNo                varchar(20)              not null comment '客户资金账号',
    currencyGroupNo          varchar(10)              not null comment '币种组号',
    currencyNo               varchar(10)                       comment '币种号(为空表示币种组基币资金)',
    tradeRate                decimal(22, 8) default 0 not null comment '交易汇率',
    futureAlg                char(1)                  not null comment '期货算法',
    optionAlg                char(1)                  not null comment '期权算法',
    preBalance               decimal(22, 8) default 0 not null comment '上日结存',
    preUnExpProfit           decimal(22, 8) default 0 not null comment '上日未到期平盈',
    preLMEPositionProfit     decimal(22, 8) default 0 not null comment '上日LME持仓平盈',
    preEquity                decimal(22, 8) default 0 not null comment '上日权益',
    preAvailable1            decimal(22, 8) default 0 not null comment '上日可用',
    preMarketEquity          decimal(22, 8) default 0 not null comment '上日市值权益',
    cashInValue              decimal(22, 8) default 0 not null comment '入金',
    cashOutValue             decimal(22, 8) default 0 not null comment '出金',
    cashAdjustValue          decimal(22, 8) default 0 not null comment '资金调整',
    cashPledged              decimal(22, 8) default 0 not null comment '质押资金',
    frozenFee                decimal(22, 8) default 0 not null comment '冻结手续费',
    frozenDeposit            decimal(22, 8) default 0 not null comment '冻结保证金',
    accountFee               decimal(22, 8) default 0 not null comment '客户手续费包含交割手续费',
    swapInValue              decimal(22, 8) default 0 not null comment '汇入资金',
    swapOutValue             decimal(22, 8) default 0 not null comment '汇出资金',
    premiumIncome            decimal(22, 8) default 0 not null comment '权利金收取',
    premiumPay               decimal(22, 8) default 0 not null comment '权利金支付',
    closeProfit              decimal(22, 8) default 0 not null comment '平仓盈亏',
    frozenFund               decimal(22, 8) default 0 not null comment '冻结资金',
    unExpProfit              decimal(22, 8) default 0 not null comment '未到期平盈',
    expProfit                decimal(22, 8) default 0 not null comment '到期平仓盈亏',
    positionProfit           decimal(22, 8) default 0 not null comment '不含LME持仓盈亏',
    lmePositionProfit        decimal(22, 8) default 0 not null comment 'LME持仓盈亏',
    optionMarketValue        decimal(22, 8) default 0 not null comment '期权市值',
    accountIntialMargin      decimal(22, 8) default 0 not null comment '客户初始保证金',
    accountMaintenanceMargin decimal(22, 8) default 0 not null comment '客户维持保证金',
    upperInitalMargin        decimal(22, 8) default 0 not null comment '上手初始保证金',
    upperMaintenanceMargin   decimal(22, 8) default 0 not null comment '上手维持保证金',
    discount                 decimal(22, 8) default 0 not null comment 'LME贴现',
    balance                  decimal(22, 8) default 0 not null comment '当日结存',
    equity                   decimal(22, 8) default 0 not null comment '当日权益',
    available                decimal(22, 8) default 0 not null comment '当日可用',
    canDraw                  decimal(22, 8) default 0 not null comment '可提取',
    marketEquity             decimal(22, 8) default 0 not null comment '账户市值',
    authMoney                decimal(22, 8) default 0 not null comment '授信资金',
    unique index (`accountId`, `brokerNo`, `accountNo`, `currencyNo`)
) comment '外盘期货资金账号资金信息表';

drop table if exists WpfuturesAccountFeeRent;
create table WpfuturesAccountFeeRent
(
    id              bigint                            not null comment '主键' primary key,
    accountId       bigint                            not null comment 'AM平台账户ID',
    brokerNo        varchar(10)                       not null comment '经纪商编码',
    accountNo       varchar(21)                       not null comment '客户资金账号',
    exchangeNo      varchar(11)                       not null comment '交易所代码',
    commodityType   char                              not null comment '品种类型',
    commodityNo     varchar(11)                       not null comment '品种编码',
    matchSource     char                              not null comment '成交来源',
    calculateMode   char                              not null comment '计算方式',
    currencyGroupNo varchar(11)                       not null comment '币种组编号',
    currencyNo      varchar(11)                       not null comment '币种编号',
    openCloseFee    decimal(22, 8) default 0.00000000 not null comment '开平手续费',
    closeTodayFee   decimal(22, 8) default 0.00000000 not null comment '平今手续费',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `commodityType`, `commodityNo`)
) comment '外盘期货客户手续费计算参数信息表';

drop table if exists WpfuturesAccountMarginRent;
create table WpfuturesAccountMarginRent
(
    id                      bigint                            not null comment '主键' primary key,
    accountId               bigint                            not null comment 'AM平台账户ID',
    brokerNo                varchar(10)                       not null comment '经纪商编码',
    accountNo               varchar(21)                       not null comment '客户资金账号',
    exchangeNo              varchar(11)                       not null comment '交易所代码',
    commodityType           char                              not null comment '品种类型',
    commodityNo             varchar(11)                       not null comment '品种编码',
    contractNo              varchar(11)                       not null comment '合约代码',
    strikePrice             varchar(11)                       not null comment '执行价',
    callOrPutFlag           char                              not null comment '看涨看跌',
    calculateMode           char                              not null comment '计算方式',
    currencyGroupNo         varchar(11)                       not null comment '币种组编号',
    currencyNo              varchar(11)                       not null comment '币种编号',
    initialMargin           decimal(22, 8) default 0.00000000 not null comment '买初始保证金',
    maintenanceMargin       decimal(22, 8) default 0.00000000 not null comment '买维持保证金',
    sellInitialMargin       decimal(22, 8) default 0.00000000 not null comment '卖初始保证金',
    sellMaintenanceMargin   decimal(22, 8) default 0.00000000 not null comment '卖维持保证金',
    lockMargin              decimal(22, 8) default 0.00000000 not null comment '锁仓比例（用于组合锁仓优惠）',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `commodityType`, `commodityNo`, `ContractNo`)
) comment '外盘期货客户保证金计算参数信息表';

drop table if exists WpfuturesPositionInfo;
create table WpfuturesPositionInfo
(
    id                       bigint                   not null comment '主键' primary key,
    accountId                bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                 varchar(12)              not null comment '经纪商编码',
    accountNo                varchar(20)              not null comment '客户资金帐号',
    exchangeNo               varchar(10)              not null comment '交易所编号',
    commodityType            char(1)                  not null comment '品种类型',
    commodityNo              varchar(10)              not null comment '品种编码类型',
    contractNo               varchar(10)              not null comment '合约1',
    strikePrice              varchar(10)              not null comment '执行价格',
    callOrPutFlag            char(1)                  not null comment '看张看跌',
    matchSide                char(1)                  not null comment '买入卖出',
    hedgeFlag                char(1)                  not null comment '投机保值',
    positionNo               varchar(70)              not null comment '本地持仓号，服务器编写',
    serverFlag               char(1)                  not null comment '服务器标识',
    orderNo                  varchar(20)              not null comment '委托编码',
    matchNo                  varchar(20)              not null comment '本地成交号',
    upperNo                  varchar(10)              not null comment '上手号',
    positionPrice            decimal(22, 8)           not null comment '持仓价',
    positionQty              int(11)        default 0 not null comment '持仓量',
    positionStreamId         int(11)                  not null comment '持仓流号',
    commodityCurrencyGroup   varchar(10)              not null comment '品种币种组',
    commodityCurrency        varchar(10)              not null comment '品种币种',
    calculatePrice           decimal(22, 8) default 0 not null comment '当前计算价格',
    accountInitialMargin     decimal(22, 8) default 0 not null comment '客户初始保证金',
    accountMaintenanceMargin decimal(22, 8) default 0 not null comment '客户维持保证金',
    upperInitialMargin       decimal(22, 8) default 0 not null comment '上手初始保证金',
    upperMaintenanceMargin   decimal(22, 8) default 0 not null comment '上手维持保证金',
    positionProfit           decimal(22, 8) default 0 not null comment '持仓盈亏',
    lMEPositionProfit        decimal(22, 8) default 0 not null comment 'LME持仓盈亏',
    optionMarketValue        decimal(22, 8) default 0 not null comment '期权市值',
    isHistory                char(1)                  not null comment '是否为昨仓',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `commodityNo`, `contractNo`, `positionNo`)
) comment '外盘期货持仓信息表';

drop table if exists WpfuturesPositionSummaryInfo;
create table WpfuturesPositionSummaryInfo
(
    id                       bigint                   not null comment '主键' primary key,
    accountId                bigint(20)               not null comment 'AM平台账户ID',
    brokerNo                 varchar(12)              not null comment '经纪商编码',
    accountNo                varchar(20)              not null comment '客户资金帐号',
    exchangeNo               varchar(10)              not null comment '交易所编号',
    commodityType            char(1)                  not null comment '品种类型',
    commodityNo              varchar(10)              not null comment '品种编码类型',
    contractNo               varchar(10)              not null comment '合约1',
    strikePrice              varchar(10)              not null comment '执行价格',
    callOrPutFlag            char(1)                  not null comment '看张看跌',
    matchSide                char(1)                  not null comment '买入卖出',
    positionPrice            decimal(22, 8)           not null comment '持仓价',
    positionQty              int(11)        default 0 not null comment '持仓量',
    HisPositionQty           int(11)        default 0 not null comment '历史持仓量',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `commodityNo`, `contractNo`, `matchSide`)
) comment '外盘期货持仓汇总表';

drop table if exists WpfuturesOrderInfo;
create table WpfuturesOrderInfo
(
    id                    bigint                   not null comment '主键' primary key,
    accountId             bigint(20)               not null comment 'AM平台账户ID',
    brokerNo              varchar(12)              not null comment '经纪商编码',
    accountNo             varchar(20)              not null comment '客户资金帐号',
    exchangeNo            varchar(10)              not null comment '交易所编号',
    commodityType         char(1)                  not null comment '品种类型',
    commodityNo           varchar(10)              not null comment '品种编码类型',
    contractNo            varchar(10)              not null comment '合约1',
    strikePrice           varchar(10)                       comment '执行价格1',
    callOrPutFlag         char(1)                           comment '看张看跌1',
    contractNo2           varchar(10)                       comment '合约2',
    strikePrice2          varchar(10)                       comment '执行价格2',
    callOrPutFlag2        char(1)                           comment '看张看跌2',
    orderType             char(1)                  not null comment '委托类型',
    orderSource           char(1)                  not null comment '委托来源',
    timeInForce           char(1)                  not null comment '委托有效类型',
    expireTime            varchar(32)                       comment '有效日期(GTD情况下使用)',
    isRiskOrder           char(1)                  not null comment '是否风险报单',
    orderSide             char(1)                  not null comment '买入卖出',
    positionEffect        char(1)                  not null comment '开平标志1',
    positionEffect2       char(1)                  not null comment '开平标志2',
    inquiryNo             varchar(50)                       comment '询价号',
    hedgeFlag             char(1)                  not null comment '投机保值',
    orderPrice            decimal(22, 8) default 0 not null comment '委托价格1',
    orderPrice2           decimal(22, 8) default 0 not null comment '委托价格2，做市商应价使用',
    stopPrice             decimal(22, 8) default 0 not null comment '触发价格',
    orderQty              int(11)        default 0 not null comment '委托数量',
    orderMinQty           int(11)        default 0 not null comment '最小成交量',
    refInt                int(11)        default 0 not null comment '整型参考值',
    refDouble             decimal(22, 8) default 0 not null comment '浮点参考值',
    refString             varchar(50)                       comment '字符串参考值',
    minClipSize           int(11)        default 0 not null comment '冰山单最小随机量',
    maxClipSize           int(11)        default 0 not null comment '冰山单最大随机量',
    licenseNo             varchar(50)              not null comment '软件授权号',
    serverFlag            char(1)                  not null comment '服务器标识',
    orderNo               varchar(20)              not null comment '委托编码',
    clientOrderNo         varchar(50)              not null comment '客户端本地委托编号',
    clientID              varchar(1024)                     comment '客户子账号',
    tacticsType           varchar(32)              not null comment '策略单类型',
    triggerCondition      char(1)                  not null comment '触发条件',
    triggerPriceType      char(1)                  not null comment '触发价格类型',
    addOneIsValid         char(1)                  not null comment '是否T+1有效',
    clientLocalIP         varchar(40)              not null comment '终端本地IP',
    clientMac             varchar(32)              not null comment '终端本地Mac地址',
    clientIP              varchar(40)              not null comment '终端网络地址',
    orderStreamID         int(11)        default 0 not null comment '委托流水号',
    upperNo               varchar(10)                       comment '上手号',
    upperChannelNo        varchar(10)                       comment '上手通道号',
    orderLocalNo          varchar(20)                       comment '本地号',
    upperStreamID         int(11)                  not null comment '上手流号',
    orderSystemNo         varchar(50)                       comment '系统号',
    orderExchangeSystemNo varchar(50)                       comment '交易所系统号',
    orderParentSystemNo   varchar(50)                       comment '父单系统号',
    orderInsertUserNo     varchar(20)              not null comment '下单人',
    orderInsertTime       varchar(32)              not null comment '下单时间',
    orderCommandUserNo    varchar(20)                       comment '录单操作人',
    orderUpdateUserNo     varchar(20)                       comment '委托更新人',
    orderUpdateTime       varchar(32)                       comment '委托更新时间',
    orderState            char(1)                  not null comment '委托状态',
    orderMatchPrice       decimal(22, 8) default 0 not null comment '成交价1',
    orderMatchPrice2      decimal(22, 8) default 0 not null comment '成交价2',
    orderMatchQty         int(11)        default 0 not null comment '成交量1',
    orderMatchQty2        int(11)        default 0 not null comment '成交量2',
    errorCode             int(11)        default 0 not null comment '最后一次操作错误信息码',
    errorText             varchar(50)                       comment '错误信息',
    isBackInput           char(1)                  not null comment '是否为录入委托单',
    isDeleted             char(1)                  not null comment '委托成交删除标',
    isAddOne              char(1)                  not null comment '是否为T+1单',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `contractNo`, `orderNo`)
) comment '外盘期货委托订单表';

drop table if exists WpfuturesFillInfo;
create table WpfuturesFillInfo
(
    id                  bigint                   not null comment '主键' primary key,
    accountId           bigint(20)               not null comment 'AM平台账户ID',
    brokerNo            varchar(12)              not null comment '经纪商编码',
    accountNo           varchar(20)              not null comment '客户资金帐号',
    exchangeNo          varchar(10)              not null comment '交易所编号',
    commodityType       char(1)                  not null comment '品种类型',
    commodityNo         varchar(10)              not null comment '品种编码类型',
    contractNo          varchar(10)              not null comment '合约1',
    strikePrice         varchar(10)              not null comment '执行价格',
    callOrPutFlag       char(1)                  not null comment '看张看跌',
    matchSource         char(1)                  not null comment '委托来源',
    matchSide           char(1)                  not null comment '买入卖出',
    positionEffect      char(1)                  not null comment '开平标志1',
    serverFlag          char(1)                  not null comment '服务器标识',
    orderNo             varchar(20)              not null comment '委托编码',
    orderSystemNo       varchar(50)              not null comment '系统号',
    matchNo             varchar(20)              not null comment '本地成交号',
    upperMatchNo        varchar(70)              not null comment '上手成交号',
    exchangeMatchNo     varchar(70)              not null comment '交易所成交号',
    matchDateTime       varchar(32)              not null comment '成交时间',
    upperMatchDateTime  varchar(32)              not null comment '上手成交时间',
    upperNo             varchar(10)              not null comment '上手号',
    matchPrice          decimal(22, 8) default 0 not null comment '成交价',
    matchQty            int(11)                  not null comment '成交量',
    isDeleted           char(1)                  not null comment '委托成交删除标',
    isAddOne            char(1)                  not null comment '是否为T+1单',
    feeCurrencyGroup    varchar(10)              not null comment '客户手续费币种组',
    feeCurrency         varchar(10)              not null comment '客户手续费币种',
    feeValue            decimal(22, 8) default 0 not null comment '手续费',
    isManualFee         char(1)                  not null comment '人工客户手续费标记',
    closePrositionPrice decimal(22, 8) default 0 not null comment '指定价格平仓',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `contractNo`, `matchNo`)
) comment '外盘期货成交表';

drop table if exists WpfuturesOrderInfoHis;
create table WpfuturesOrderInfoHis
(
    id                    bigint                   not null comment '主键' primary key,
    accountId             bigint(20)               not null comment 'AM平台账户ID',
    brokerNo              varchar(12)              not null comment '经纪商编码',
    accountNo             varchar(20)              not null comment '客户资金帐号',
    exchangeNo            varchar(10)              not null comment '交易所编号',
    commodityType         char(1)                  not null comment '品种类型',
    commodityNo           varchar(10)              not null comment '品种编码类型',
    contractNo            varchar(10)              not null comment '合约1',
    strikePrice           varchar(10)                       comment '执行价格1',
    callOrPutFlag         char(1)                           comment '看张看跌1',
    contractNo2           varchar(10)                       comment '合约2',
    strikePrice2          varchar(10)                       comment '执行价格2',
    callOrPutFlag2        char(1)                           comment '看张看跌2',
    orderType             char(1)                  not null comment '委托类型',
    orderSource           char(1)                  not null comment '委托来源',
    timeInForce           char(1)                  not null comment '委托有效类型',
    expireTime            varchar(32)                       comment '有效日期(GTD情况下使用)',
    isRiskOrder           char(1)                  not null comment '是否风险报单',
    orderSide             char(1)                  not null comment '买入卖出',
    positionEffect        char(1)                  not null comment '开平标志1',
    positionEffect2       char(1)                  not null comment '开平标志2',
    inquiryNo             varchar(50)                       comment '询价号',
    hedgeFlag             char(1)                  not null comment '投机保值',
    orderPrice            decimal(22, 8) default 0 not null comment '委托价格1',
    orderPrice2           decimal(22, 8) default 0 not null comment '委托价格2，做市商应价使用',
    stopPrice             decimal(22, 8) default 0 not null comment '触发价格',
    orderQty              int(11)        default 0 not null comment '委托数量',
    orderMinQty           int(11)        default 0 not null comment '最小成交量',
    refInt                int(11)        default 0 not null comment '整型参考值',
    refDouble             decimal(22, 8) default 0 not null comment '浮点参考值',
    refString             varchar(50)                       comment '字符串参考值',
    minClipSize           int(11)        default 0 not null comment '冰山单最小随机量',
    maxClipSize           int(11)        default 0 not null comment '冰山单最大随机量',
    licenseNo             varchar(50)              not null comment '软件授权号',
    serverFlag            char(1)                  not null comment '服务器标识',
    orderNo               varchar(20)              not null comment '委托编码',
    clientOrderNo         varchar(50)              not null comment '客户端本地委托编号',
    clientID              varchar(1024)                     comment '客户子账号',
    tacticsType           varchar(32)              not null comment '策略单类型',
    triggerCondition      char(1)                  not null comment '触发条件',
    triggerPriceType      char(1)                  not null comment '触发价格类型',
    addOneIsValid         char(1)                  not null comment '是否T+1有效',
    clientLocalIP         varchar(40)              not null comment '终端本地IP',
    clientMac             varchar(32)              not null comment '终端本地Mac地址',
    clientIP              varchar(40)              not null comment '终端网络地址',
    orderStreamID         int(11)        default 0 not null comment '委托流水号',
    upperNo               varchar(10)                       comment '上手号',
    upperChannelNo        varchar(10)                       comment '上手通道号',
    orderLocalNo          varchar(20)                       comment '本地号',
    upperStreamID         int(11)                  not null comment '上手流号',
    orderSystemNo         varchar(50)                       comment '系统号',
    orderExchangeSystemNo varchar(50)                       comment '交易所系统号',
    orderParentSystemNo   varchar(50)                       comment '父单系统号',
    orderInsertUserNo     varchar(20)              not null comment '下单人',
    orderInsertTime       varchar(32)              not null comment '下单时间',
    orderCommandUserNo    varchar(20)                       comment '录单操作人',
    orderUpdateUserNo     varchar(20)                       comment '委托更新人',
    orderUpdateTime       varchar(32)                       comment '委托更新时间',
    orderState            char(1)                  not null comment '委托状态',
    orderMatchPrice       decimal(22, 8) default 0 not null comment '成交价1',
    orderMatchPrice2      decimal(22, 8) default 0 not null comment '成交价2',
    orderMatchQty         int(11)        default 0 not null comment '成交量1',
    orderMatchQty2        int(11)        default 0 not null comment '成交量2',
    errorCode             int(11)        default 0 not null comment '最后一次操作错误信息码',
    errorText             varchar(50)                       comment '错误信息',
    isBackInput           char(1)                  not null comment '是否为录入委托单',
    isDeleted             char(1)                  not null comment '委托成交删除标',
    isAddOne              char(1)                  not null comment '是否为T+1单',
    unique index (`accountId`, `brokerNo`, `accountNo`, `exchangeNo`, `contractNo`, `orderNo`)
) comment '外盘期货委托订单历史表';
